spring:
  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: secret
    driveClassName: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true

server:
  port: 8080

security:
  jwt:
    secret: "super_secret_key_bravo_credit_client_2026_very_long_1234567890"




logging:
  level:
    com.bravo: DEBUG
    org.hibernate: ERROR
    org.springframework: ERROR
    root: ERROR
eureka:
  client:
    enabled: false


### Configuracion que no debe ir en el configuration service


